# Generated by Django 3.0.6 on 2020-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbohydrate', models.FloatField()),
            ],
            options={
                'ordering': ['food_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_description', models.TextField()),
                ('foodrecipe_ingredients', models.ManyToManyField(to='app_food.Food')),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_description', models.CharField(max_length=200)),
                ('userfood_fridge', models.ManyToManyField(to='app_food.Food')),
                ('userrecipe_savedrecipes', models.ManyToManyField(to='app_food.Recipes')),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
    ]
